// <auto-generated />
namespace RepositorioGenericoMVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IniciandProyecto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IniciandProyecto));
        
        string IMigrationMetadata.Id
        {
            get { return "201807151818005_IniciandProyecto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
